Disable not found tasks

diff --git a/.github/workflows/tasks.yml b/.github/workflows/tasks.yml
--- a/.github/workflows/tasks.yml
+++ b/.github/workflows/tasks.yml
@@ -111,43 +111,43 @@ jobs:
         run: |
           python quickstatements.py --batchname AppleTVIDs <output.csv
 
-  not_found:
-    runs-on: ubuntu-latest
-
-    strategy:
-      fail-fast: false
-      matrix:
-        property:
-          - "P6398"
-          - "P9586"
-
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-
-      - name: Run script
-        run: |
-          set -o pipefail
-          python not_found_${{ matrix.property }}.py | tee output.csv
-
-      - name: Login
-        env:
-          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
-        run: |
-          python pwb.py login
-
-      - name: Process batch
-        run: |
-          python deprecatestatements.py <output.csv
+#  not_found:
+#    runs-on: ubuntu-latest
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        property:
+#          - "P6398"
+#          - "P9586"
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#
+#      - name: Set up Python 3.9
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.9
+#
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install -r requirements.txt
+#
+#      - name: Run script
+#        run: |
+#          set -o pipefail
+#          python not_found_${{ matrix.property }}.py | tee output.csv
+#
+#      - name: Login
+#        env:
+#          WIKIDATA_PASSWORD: ${{ secrets.WIKIDATA_PASSWORD }}
+#        run: |
+#          python pwb.py login
+#
+#      - name: Process batch
+#        run: |
+#          python deprecatestatements.py <output.csv
 
 #  matches:
 #    runs-on: ubuntu-latest
